In [81]:
import numpy as np
from astropy.io import fits
from astropy.io import ascii 
from match import match
from SED_v8 import Flux_to_Lum

In [82]:
with fits.open('/Users/connor_auge/Research/Disertation/catalogs/U2012_GOALS.fits') as hdul:
    data = hdul[1].data
    cols = hdul[1].columns
    
table1 = ascii.read('/Users/connor_auge/Downloads/U_table1_ascii.csv')

table10 = ascii.read('/Users/connor_auge/Downloads/U_table10_ascii.csv')

In [83]:
phot_ID = data['ID']
phot_H = data['H']

dist_ID = np.asarray(table1['RBGS Name'])
dist = np.asarray(table1['D_L'])
Lir = np.asarray(table1['log(L_IR)_IRAS'])

ix, iy = match(phot_ID, dist_ID)
phot_ID_match = phot_ID[ix]
H_match = phot_H[ix]
dist_match = dist[iy]
dist_ID_match = dist_ID[iy]
Lir_match = Lir[iy]

mass_ID = np.asarray(table10['RBGS Name'])
mass = np.asarray(table10['log (M_H)_Sal'])

In [90]:
Fnu = H_match*1E-23
nu = 10**14.26
# nu = 3E10/1.65E-4
nuFnu = Fnu*nu

L_ulirg = Flux_to_Lum(nuFnu[Lir_match > 12],z=0,d=dist_match[Lir_match > 12]*1E6,distance=True)
L = Flux_to_Lum(nuFnu,z=0,d=dist_match*1E6,distance=True)
L_solar = np.log10(L) - np.log10(3.8E33)

In [91]:
np.median(np.log10(L_ulirg)) - np.log10(3.8E33)

10.711213604215061

In [74]:
ix, iy = match(phot_ID_match, mass_ID)
phot_ID_match2 = phot_ID_match[ix]
L_solar_match = L_solar[ix]
mass_ID_match = mass_ID[iy]
mass_match = mass[iy]

In [75]:
L_solar

array([10.57635136,  9.84789886, 10.54817135, 10.23806644, 10.38614626,
       10.44690599, 10.5886743 , 10.64835827,  9.95308087, 10.60494372,
       10.08063334, 10.26282221, 10.12222677, 10.72585326, 10.12531982,
       10.13097653, 10.7112136 , 10.59492291,  9.76020405, 10.8282311 ,
       10.42220046, 10.69129726, 10.54094959, 10.68174903, 10.57412811,
       10.39320357, 10.42254418, 10.62047338, 10.81952709, 10.93906249,
       10.48986292, 10.31756083, 10.61650588, 10.6544102 , 10.81984169,
       10.62537177, 10.7448118 , 10.99881074, 10.37937957, 10.85807528,
       10.37618348, 10.79864876, 10.74358868, 11.38427139, 10.42590017,
       10.7637564 , 10.59022034, 10.67623181])

In [76]:
len(mass_ID_match)

11

In [77]:
mass_match

array([10.58, 10.84, 11.03, 11.14, 10.63, 10.47, 10.83, 10.97, 10.81,
       10.97, 11.17])

In [79]:
(mass_match)/(L_solar_match)

array([1.01510723, 1.02067013, 1.01945306, 1.01836881, 1.01335929,
       1.01477473, 1.02010964, 1.01387805, 1.01737617, 1.02095785,
       1.01556434])

In [80]:
np.nanmedian(mass_match/L_solar_match)

1.017376166306386