In [2]:
import numpy as np 
from astropy.io import fits 
from astropy.io import ascii 
from match import match

In [3]:
bhm_file = ascii.read('/Users/connor_auge/Downloads/Merged_masses (1).csv')
auge_file = ascii.read('/Users/connor_auge/Research/Disertation/AHA_SED_paper1_materials/Tables/datafileA1.txt')
s82x_cat = fits.open('/Users/connor_auge/Downloads/S82X_catalog_with_photozs_mbh_2024_release.fits')
s82x_data = s82x_cat[1].data
s82x_cols = s82x_cat[1].columns
s82x_cat.close()

In [4]:
s82x_cols

ColDefs(
    name = 'MSID'; format = 'J'
    name = 'REC_NO'; format = 'J'
    name = 'OBSID'; format = '10A'
    name = 'XRAY_SRC'; format = '11A'
    name = 'XRAY_RA'; format = 'D'
    name = 'XRAY_DEC'; format = 'D'
    name = 'XRAY_RADEC_ERR'; format = 'E'
    name = 'SOFT_FLUX'; format = 'E'
    name = 'SOFT_FLUX_ERROR'; format = 'E'
    name = 'SOFT_FLUX_ERROR_HIGH'; format = 'E'
    name = 'SOFT_FLUX_ERROR_LOW'; format = 'E'
    name = 'SOFT_COUNTS'; format = 'E'
    name = 'SOFT_DETML'; format = 'E'
    name = 'SOFT_LUM'; format = 'E'
    name = 'HARD_FLUX'; format = 'E'
    name = 'HARD_FLUX_ERROR'; format = 'E'
    name = 'HARD_FLUX_ERROR_HIGH'; format = 'E'
    name = 'HARD_FLUX_ERROR_LOW'; format = 'E'
    name = 'HARD_COUNTS'; format = 'E'
    name = 'HARD_DETML'; format = 'E'
    name = 'HARD_LUM'; format = 'E'
    name = 'FULL_FLUX'; format = 'E'
    name = 'FULL_FLUX_ERROR'; format = 'E'
    name = 'FULL_FLUX_ERROR_HIGH'; format = 'E'
    name = 'FULL_FLUX_ERROR_LOW'; f

In [5]:
print(s82x_data['rec_no'])
print(s82x_data['msid'])

s82x_ID = []
for i in range(len(s82x_data['msid'])):
    if s82x_data['msid'][i] == 0:
        s82x_ID.append(s82x_data['rec_no'][i])
    else:
        s82x_ID.append(s82x_data['msid'][i]) 

s82x_ID = np.asarray(s82x_ID,dtype='int64')
s82x_Lx = s82x_data['FULL_LUM']
# s82x_ID = s82x_data['OBSID']
s82x_RA = s82x_data['Xray_RA'] 
s82x_Dec = s82x_data['Xray_Dec'] 
s82x_z = s82x_data['SPEC_Z']

[   0    0    0 ... 5218 5219 5220]
[15288 15292 15293 ...     0     0     0]


In [6]:
auge_field = auge_file['Field']
auge_ID = auge_file['xID']

auge_ID = auge_ID[auge_field == 'Stripe82X']
auge_ID = np.asarray(auge_ID,dtype='int64')
print('Auge Sample: ',len(auge_ID))

bhm_ID = np.asarray(bhm_file['extracted_id'],dtype='int64')

print('BHM Sample: ',len(bhm_ID))

print(type(auge_ID[0]))
print(type(bhm_ID[0]))

Auge Sample:  529
BHM Sample:  388
<class 'numpy.int64'>
<class 'numpy.int64'>


In [7]:
ix, iy = match(auge_ID,bhm_ID)

print('Auge Sample Match: ',len(auge_ID[ix]))
print('BHM Sample Match: ',len(bhm_ID[iy]))

print(bhm_ID[iy])

Auge Sample Match:  7
BHM Sample Match:  7
[2731 3070 3274 3376 4029 4292 4816]


In [22]:
with fits.open('/Users/connor_auge/Research/Disertation/xcigale/_data_output_final_new/S82X_4/results.fits') as hdul:
    data = hdul[1].data 
    cols = hdul[1].columns

ID = 4816
ids = data['id']
lagn = np.log10(data['bayes.agn.luminosity'])+7
lagn_err = np.log10(data['bayes.agn.luminosity_err'])+7

print(lagn[ids == ID])
print(lagn_err[ids == ID])


[43.87255943]
[43.73968975]


In [8]:
ix, iy = match(s82x_ID,bhm_ID)


print('S82X Sample Match: ',len(s82x_ID[ix]))
print('BHM Sample Match: ',len(bhm_ID[iy]))

S82X Sample Match:  76
BHM Sample Match:  76


In [9]:
print(s82x_ID[ix])

[ 170  178  275  284  350  356  438  445  482  564  578  765  803  973
 1076 1213 1224 1300 1344 1391 1514 1637 1638 1659 1860 1913 1917 1922
 2035 2103 2105 2242 2260 2404 2602 2630 2680 2731 2892 2969 3032 3036
 3070 3233 3274 3376 3466 3562 3584 3677 3700 3832 3978 4029 4050 4292
 4299 4315 4341 4345 4355 4362 4368 4402 4415 4431 4434 4447 4518 4522
 4575 4607 4667 4700 4816 5109]


In [10]:

for i in range(len(s82x_ID)):
    print(s82x_ID[i],s82x_RA[i],s82x_Dec[i],s82x_z[i])

15288 29.212190628051758 -0.7596653699874878 1.79478
15292 29.32048797607422 -0.8845500349998474 0.4222689
15293 29.356101989746094 -0.853904128074646 -99.0
15295 29.273893356323242 -0.8747815489768982 1.4723456
15296 29.304973602294922 -0.9878523349761963 0.4409238
15297 29.221399307250977 -0.772914469242096 0.614833
15303 29.209503173828125 0.8856979012489319 1.653214
15304 29.222265243530273 0.9049625396728516 1.6600296
15306 29.14021110534668 0.9635860919952393 0.6050189
15307 29.221872329711914 0.7369799613952637 0.73088205
15308 29.22968292236328 0.7656712532043457 0.4359102
27923 334.51275634765625 0.08011411875486374 -99.0
27925 334.59130859375 0.24413909018039703 -99.0
27926 334.4971923828125 0.4245149493217468 -99.0
27927 334.5952453613281 0.26779356598854065 -99.0
27932 334.3713073730469 0.3339650630950928 -99.0
27975 334.3040466308594 0.4121021330356598 1.913
27977 334.4461364746094 0.44123736023902893 -99.0
27978 334.4226989746094 0.09732600301504135 -99.0
27982 334.437652

In [11]:
with fits.open('/Users/connor_auge/Downloads/Xray_15_comb4_slim23.fits') as hdul:
    check_cols = hdul[1].columns
    check_data = hdul[1].data

In [12]:
check_cols

ColDefs(
    name = 'XID_S82XL'; format = 'I'
    name = 'RA'; format = 'D'
    name = 'DEC'; format = 'D'
    name = 'POS_ERR'; format = 'D'
    name = 'IAUNAME_4XMM'; format = '21A'
    name = 'OBS_ID_4XMM'; format = '142A'
    name = 'RA_4XMM'; format = 'D'
    name = 'DEC_4XMM'; format = 'D'
    name = 'EP_1_FLUX_4XMM'; format = 'D'
    name = 'EP_1_FLUX_ERR_4XMM'; format = 'D'
    name = 'EP_2_FLUX_4XMM'; format = 'D'
    name = 'EP_2_FLUX_ERR_4XMM'; format = 'D'
    name = 'EP_3_FLUX_4XMM'; format = 'D'
    name = 'EP_3_FLUX_ERR_4XMM'; format = 'D'
    name = 'EP_4_FLUX_4XMM'; format = 'D'
    name = 'EP_4_FLUX_ERR_4XMM'; format = 'D'
    name = 'EP_5_FLUX_4XMM'; format = 'D'
    name = 'EP_5_FLUX_ERR_4XMM'; format = 'D'
    name = 'EP_8_FLUX_4XMM'; format = 'D'
    name = 'EP_8_FLUX_ERR_4XMM'; format = 'D'
    name = 'EP_8_RATE_4XMM'; format = 'D'
    name = 'EP_8_RATE_ERR_4XMM'; format = 'D'
    name = 'EP_8_CTS_4XMM'; format = 'D'
    name = 'EP_8_CTS_ERR_4XMM'; format = 'D'
 

In [16]:
check_ID = check_data['XID_S82XL']

In [23]:
ix, iy = match(s82x_ID,check_ID)

print(len(s82x_ID),len(check_ID))
print(len(s82x_ID[ix]))

6181 23626
5223


In [19]:
ix, iy = match(bhm_ID,check_ID)

print(len(bhm_ID[ix]))

388


In [20]:
ix, iy = match(auge_ID,check_ID)

print(len(auge_ID[ix]))

507


In [22]:
ix, iy = match(auge_ID, s82x_ID)

print(len(auge_ID[ix]))

529
